[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build && chmod +x start.sh"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
