services:
  # Backend API
  - type: web
    name: task-pilot-backend
    runtime: docker
    region: oregon
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile.prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
