services:
  # Backend API
  - type: web
    name: task-pilot-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm install typescript @types/node --save-dev && npx tsc
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
